config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :users, except: [:new]

  resources :articles
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email = email.downcase }
  #to ensure that the user is present and uniq -  the length to ensure that the number of the letters are at least Ex: 2 or 3 or 4
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\.-]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only:[:edit, :update, :show, :destroy]


  def index
    @articles = Article.all
  end


  def new
    @article = Article.new
  end

def edit

end


  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save # do something
      flash[:success] = "Article was successfully created" # this is message for a user
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

def update
  if @article.update(article_params)
    flash[:success] = "Article was succssfully updated"
    redirect_to article_path(@article)
  else
    render 'edit'
  end
end


  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

    def article_params
    params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
def create
  @user = User.new(user_params)
  if @user.save
      flash[:success] = "welcome to the zain #{@user.username}"
      redirect_to articles_path
  else
    render 'new'
  end
end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to article_path
    else
      render 'edit'
    end

  end


  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-sm-12">
      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"})  do |f| %>
            <div class="form-group">
              <div class="control-label col-sm-2">
            <%= f.label :title %>
              </div>
              <div class="col-sm-10">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
              </div>
            </div>
            <div class="form-group">
              <div class="control-label col-sm-2">

              <%= f.label :description %>
              </div>
              <div class="col-sm-10">
                <%= f.text_area :description, rows: 4, class: "form-control", placeholder: "Body of article" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10"><br>
                <%= f.submit class: 'btn btn-primary btn-lg' %>
              </div>
            </div>
    <% end %>

          <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
          </div>
        </div>
      </div>

app/views/articles/edit.html.erb
<h1 align="center"> Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles </h1>




<% @articles.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">

            <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
          <small> Created by: <%= article.user.username if article.user %>,
          <%= time_ago_in_words(article.created_at) %> ago,
          last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>

          </div>
        </div>
        <div class="article-actions">
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(article), method: :delete,
                      data: {confirm: "Are you sure you want to delete the article?"},
                      class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1 align="center">Create an  article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>

  <div class="article-actions">
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this article", article_path(@article), method: :delete,
        data: { confirm: "Are you sure you want to delete the article?" },
        class: "btn btn-xs btn-danger" %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
      <small>
        Copyright &copy; <a href="https://www.udemy.com">The compete Ruby on Rails Developer</a>
        by <a href="http://www.google.com"> Tarek Al-Balhawan</a>
      </small>
      <nav>
          <ul>
            <li><%= link_to "About", about_path %></li>
          </ul>
      </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">

  <div class="col-sm-12 col-sm-offset-1">

    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>

    <% end %>

  </div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to "zain", root_path, class: "navbar brand", id: "logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

      <%= link_to "Articles", articles_path %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <%= link_to "New Article", new_article_path %>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zain</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/pages/about.html.erb
<h1>This is About Page</h1>



<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">

  <h1>ZAIN</h1>
  <%=  link_to "Sign up now", "#", class: "btn btn-warning btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>

              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>

            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-10">


          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">

          <%= f.label :email %>
        </div>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">

          <%= f.label :password %>
        </div>
        <div class="col-sm-10">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10"><br>
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>

    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1 align="center">Sign up for Zain</h1>

<%= render 'form' %>